### ISSUE TITLE
Seperate out unit tests from QA tests

### ISSUE THREAD

**Issue by jodygarnett** [locationtech/geogig#191]
Building master takes a long time; it looks like some of the unit tests are actually stress tests. Currently my build is stuck on:

````
LogOp took 7.871 ms
Iterated 1,000 commits in 51.87 ms
############### Warm up done.
***********
Creating 1,000 commits...
1,000 created in 1.459 min
LogOp took 1.296 ms
Iterated 1,000 commits in 25.60 ms
***********
Creating 10,000 commits...
10,000 created in 13.65 min
LogOp took 1.323 ms
Iterated 10,000 commits in 175.5 ms
***********
````

Indeed creating 10,000 commits seem to take more than building/testing the rest of the codebase. Can we isolate this into a "StressTest" profile and run it nightly? Having these long tests in the mix prevents developers from performing quick unit tests after a change.

**Comment by emerkle826** [comment]
@jodygarnett Stress tests have been hooked with a profile in the `dev` branch, I believe with commits aec19cd and 9e43110. Once we merge `dev` into `master`, this shouldn't be an issue anymore.

**Comment by jodygarnett** [comment]
Sounds good, let's close this when those are merged to master?

**Comment by groldan** [comment]
done
