### ISSUE TITLE
Replace jGridShift

### ISSUE THREAD

**Issue by cuttlefish** [locationtech/geogig#3]
As part of the IP review for LocationTech, jGridShift has been rejected due to its LGPL licence.
http://jgridshift.sourceforge.net/
We'll have to find an alternative or rewrite this component under a permissible licence.

**Comment by cuttlefish** [comment]
The tests pass when jGridShift is excluded.
For now we'll exclude it. If the user has it installed it should work for them.
The project is dead, so it may be subsumed into GeoTools in which case it's no longer an issue from our perspective.

**Comment by groldan** [comment]
excluded from geotools already, closing.
