### ISSUE TITLE
 Page with Plugins and External Projects.

### ISSUE THREAD

**Issue by jlanio** [locationtech/geogig#345]
Improvement: Add to the site (brache gh-pages) a page with
Plugins and External Projects.

Examples of projects:
Link to Geogig-Desktop
Https://github.com/jlanio/Geogig-Desktop
Link to Qgis Plugin
Https://github.com/boundlessgeo/qgis-geogiglight-plugin
Link to Plugin Geserver
Http://geogig.org/docs/interaction/geoserver_ui.html

Among others.
A space for project divination using geogig.

If the improvement is desirable I will draw up a new pull request

**Comment by walker** [comment]
https://github.com/locationtech/geogig/wiki/Projects-Using-Geogig
