### ISSUE TITLE
Remove non-libraries from lib

### ISSUE THREAD

**Issue by walker** [locationtech/geogig#351]
Working to get geogig in homebrew core.
`brew audit` is required to pass before this can be submitted.

I'm auditing my the keg I created here: `brew audit --new-formula walker/geokeg/geogig`

This item says that two files need to be removed from `/lib`:

```
  * Non-libraries were installed to "/usr/local/opt/geogig/lib"
    Installing non-libraries to "lib" is discouraged.
    The offending files are:
      /usr/local/opt/geogig/lib/dependency-tree.txt
      /usr/local/opt/geogig/lib/maven-metadata-appassembler.xml
```

**Comment by jdgarrett** [comment]
This should be resolved with the latest snapshot.
