### ISSUE TITLE
GeoJSON import works for only one object

### ISSUE THREAD

**Issue by gumenikav** [locationtech/geogig#380]
I try to import json file with some objects:
<pre>
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.00134593199730245,
          -0.003571094
        ]
      },
      "properties": {
        "depth": "0",
        "depthundefined": "True",
        "exist": "1",
        "type": "3"
      },
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.00132208399735339,
          0.005472552
        ]
      },
      "properties": {
        "depth": "13",
        "depthundefined": "False",
        "exist": "1",
        "type": "1"
      },
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          0.0035084589929485,
          0.003802286
        ]
      },
      "properties": {
        "depth": "0",
        "depthundefined": "False",
        "exist": "1",
        "type": "1"
      },
    }
  ]
}
</pre>

I use "geogig geojson import "./tst.json" -d tst" command.
Only first object from FeatureCollection is added to geogig tree after this.

**Comment by emerkle826** [comment]
Hi
​ ​
Alexandr
​,


What version of GeoGig are you trying this with, and which OS? I just tried
your provided GeoJSON with GeoGig v1.1.1 (from here:
https://github.com/locationtech/geogig/releases/tag/v1.1.1) and it seems to
work as expected:

​

$ /opt/geogig/geogig/bin/geogig geojson import test.json -d "test"
Importing from GeoJSON test.json

Importing feature          (1/1)...
0%
3 features inserted in 21.65 ms

Building final tree test...

3 features tree built in 9.395 ms
100%
test.json imported successfully.
$ /opt/geogig/geogig/bin/geogig status
# On branch master
# Changes not staged for commit:
#   (use "geogig add <path/to/fid>..." to update what will be committed
#   (use "geogig checkout -- <path/to/fid>..." to discard changes in
working directory
#
#      added  test
#      added  test/feature-1
#      added  test/feature-2
#      added  test/feature-0
# 4 total.



Erik Merkle
Software Engineer | Boundless <http://boundlessgeo.com/>

<http://d32wfbeasdaw38.cloudfront.net/img/Boundless_Logo.png>

**Comment by gumenikav** [comment]
Hello!

I am not sure about version, my colleague, which in vacation now, built geogig from master's head  two  weeks ago.
OS is Windows 10.

I will try to use v1.1.1 for now and i will provide more information when my colleague returns.

**Comment by gumenikav** [comment]
I have tested V1.1.1 binaries and it works fine with GeoJson. Thank you.

**Comment by emerkle826** [comment]
I'm glad v1.1.1 worked for you. I'll try to see if there is an issue in the `master` branch (v1.2) and get it addressed if there is.

Thanks for the report.

**Comment by emerkle826** [comment]
@gumenikav It seems you have found a bug in the 1.2/master branch. I tried the exact same test, but using the latest master and it does in fact only add 1 of the 3 features. Re-opening this issue.

**Comment by emerkle826** [comment]
PR #390 Is in review to address this issue.

**Comment by jdgarrett** [comment]
Resolved with #390.
