### ISSUE TITLE
Clone command creates extra folder with name of original repo

### ISSUE THREAD

**Issue by gumenikav** [locationtech/geogig#391]
Version 1.1.1
Windows 10

I try to clone repository from "Main" folder to "Cloned" folder.
Result of my try is creation of additional folder "Main" in folder "Cloned",
but i have expected to see ".geogig" folder in "Cloned" folder.

![clone_problem](https://user-images.githubusercontent.com/26217062/31181659-8c9e6116-a92a-11e7-99e2-a502d96cff73.jpg)

**Comment by emerkle826** [comment]
@gumenikav You can not clone a repo into your current working directory. For your scenario, if you want the repository in `C:\GeoGigTest\GeoGigRepo\Main` to be cloned into a repository at `C:\GeoGigTest\GeoGigRepo\Cloned`, you will have to execute the `clone` command from `C:\GeoGigTest\GeoGigRepo` with a command like this:

`geogig clone Main Cloned`

That should clone the repo in `Main` to a peer directory `Cloned`

**Comment by gumenikav** [comment]
Ok, thanks, i will try this.
But i acted according to GeoGig tutorial example of clone command...
<pre>
mkdir ../my_new_repo
cd ../my_new_repo
geogig clone ../YOUR_FIRST_REPO
</pre>

**Comment by gumenikav** [comment]
Yes, it works in this way.
But i think it's strangely for geogig, where almost all commands have to be launch from repository directory, including **geogig init**.

**Comment by emerkle826** [comment]
The documentation in the tutorial probably needs to be revisited. It's not incorrect, however. In the tutorial example on the web page, the cloned repo will be in a folder with the same name as the repository being cloned, and the folder will be created as a sub-directory under the folder you execute the command from (in this case, ../my_new_repo/YOUR_FIRST_REPO). However, the documentation doesn't indicate that, and I see how it is misleading.

Yes, most commands do need to run from within a repository directory, however **init** and **clone** are a bit different in that they result in turning a directory into a repository. With **init**, you can initialize the current working directory as a new repository, or you can initialize a sub-directory by specifying the location. Example:

`geogig init subRepo`

would initialize a repository in a new directory called `subRepo` in the current working directory.

The **clone** operation works similar to that example, however, **clone** does not allow you to make the current working directory a clone itself. I can discuss this with the development team to see how to address this apparent inconsistency.
