### ISSUE TITLE
Change Woodstox dependency from LGPL to Apache licence

### ISSUE THREAD

**Issue by cuttlefish** [locationtech/geogig#5]
Woodstox supports either the LGPL or Apache licence. We're currently using the LGPLed jar and need to switch to the Apache one. The LGPL version will get rejected in the IP review.

**Comment by cuttlefish** [comment]
The tests pass and the LGPL library isn't downloaded.

**Comment by groldan** [comment]
dependency removed since the osm module was taken off the project onto geogig-plugins
