### ISSUE TITLE
Resolve JSONAssert IP issues 

### ISSUE THREAD

**Issue by groldan** [locationtech/geogig#84]
LocationTech CQ #[11343](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11343) JSONassert 
Current status: **withdrawn**

Depends on `org.json:json` which has a license specifying "the Software shall be used for Good, not Evil." Whilst amusing, this is not an open source license. Apparently we can get versions of this without the moral restriction, but I'm concerned that version mismatches may bite us.

**Comment by emerkle826** [comment]
this issue was resolved with https://github.com/locationtech/geogig/issues/162
