### ISSUE TITLE
Resolve Osmosis IP Issues

### ISSUE THREAD

**Issue by groldan** [locationtech/geogig#88]
LocationTech CQ #[9000](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9000) `open street map - osmosis Version: 0.43.1` 

Current status: **waiting for a response from us**

The LGPL license is a problem. It seems it may have more serious license issues.

* 13 Files contained in the OSM component appear to be licensed LGPL.  That
said, part of the hearder for those files actually indicate, "You should have
received a copy of the GNU General Public License along with this program"
which references the GPL not the LGPL.
* Three files in the Core component also provide some challenges:
 * `MultiMemberGZIPInputStream.java` sites, the class was copied directly from the workaround class provided in a sun bug.  Unfortunately the Terms of Use referenced by Oracle is not suitable for open source.
  * `DataParser.java` and `FallbackDateParser.java` indicate,  "Handles a number of different date formats encountered in OSM. This is built based on similar code in JOSM." 

**Resolution strategy:**

TBD

**Comment by emerkle826** [comment]
This issue is resolved by moving the OSM module out of https://github.com/locationtech/geogig via https://github.com/boundlessgeo/geogig-plugins/pull/1
