### ISSUE TITLE
Resolve Jettison IP Issues

### ISSUE THREAD

**Issue by groldan** [locationtech/geogig#90]
LocationTech CQ# [8992](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=8992) `jettison Version: 1.0.1` 

Current status: **waiting for a response from us**

This includes the source from `org.json:json` which is not covered by an open source license. 

**Resolution strategy:**

a) We may be able to replace the files, but potential version conflicts exist.
b) Get rid of it in favor a the [reference implementation of JSR353](http://mvnrepository.com/artifact/org.glassfish/javax.json/1.0.4)

**Comment by cuttlefish** [comment]
I think this is a direct dependency, so we could also just update it. All newer versions have an acceptable license.

**Comment by emerkle826** [comment]
This issues is resolved by https://github.com/locationtech/geogig/issues/162 and https://github.com/locationtech/geogig/issues/166
